<?php

if (!defined('SUMEDIA_BASE_VERSION')) {
    header( 'Status: 403 Forbidden' );
    header( 'HTTP/1.1 403 Forbidden' );
    exit();
}

$heading = $this->get('sumedia_base_admin_view_heading');

?>
<div class="wrap suma-wrap">

    <?php echo $heading->render(); ?>

    <div class="suma-content">
        <form class="suma-form" name="suma-urlfix-config-form" action="<?php echo admin_url('admin.php?page=sumedia&plugin=urlify&action=set-config'); ?>" method="post">
            <fieldset>
                <legend><?php echo __('Setup URL Rewrites', 'sumedia-urlify'); ?></legend>
                <div class="suma-form-option">
                    <div class="suma-form-label"><label><?php echo __('Admin URL', 'sumedia-urlify'); ?>:</label></div>
                    <div class="suma-form-input">
                        <?php echo site_url('/wp-admin'); ?> to:<br />
                        <strong><?php echo site_url(); ?>/</strong> <input name="admin_url" size="10" type="text" value="<?php echo $this->get('urls')->get('admin_url'); ?>" />
                    </div>
                </div>
                <div class="suma-form-option">
                    <div class="suma-form-label"><label><?php echo __('Login URL', 'sumedia-urlify'); ?>:</label></div>
                    <div class="suma-form-input">
                        <?php echo site_url('/login.php'); ?> to:<br />
                        <strong><?php echo site_url(); ?>/</strong> <input name="login_url" size="10" type="text" value="<?php echo $this->get('urls')->get('login_url'); ?>" />
                    </div>
                </div>
            </fieldset>
            <br />
            <div class="suma-form-actions">
                <input class="button" type="submit" name="submit" value="<?php echo __('Save URL\'s', 'sumedia-urlify'); ?>" />
                <div class="right">
                    <a href="javascript:void(0);" name="reset"><?php echo __('Reset to Wordpress Defaults', 'sumedia-urlify'); ?></a>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    (function($){

        $(document).ready(function(){

            $('form[name="suma-urlfix-config-form"] a[name="reset"]').click(function(){
                $('form[name="suma-urlfix-config-form"] input[name="admin_url"]').val('wp-admin');
                $('form[name="suma-urlfix-config-form"] input[name="login_url"]').val('wp-login.php');
            });

        });

    }(jQuery));
</script>