<?php

if (!defined('SUMEDIA_BASE_VERSION')) {
    header( 'Status: 403 Forbidden' );
    header( 'HTTP/1.1 403 Forbidden' );
    exit();
}

?>
<h3><?php echo __('Urlify', 'sumedia-urlify'); ?> <small><?php echo SUMEDIA_URLIFY_VERSION; ?></small></h3>
<small>sumedia-urlify</small>
<div class="sumedia-overview-plugin">
    <div class="sumedia-overview-plugin-description">

        <p class="notice notice-warning">
            <?php
            echo __('Important: Before you can remove this plugin you have to deactivate it.<br />
                        If you don\'t deactivate it you can harm your ADMIN_COOKIE_PATH in wp-config.php or
                        the Rewrite Rules in .htaccess file.',
                'sumedia-urlify');
            ?>
        </p>

        <p>
            <?php
            echo __('This Plugin will provide a way to disallow Access to /wp-admin/ with the renaming
                of the backends default url. It can rewrite the wp-login.php location too, so bots will
                have no chance to find the login script.',
                'sumedia-urlify');
            ?>
        </p>
    </div>
    <div class="sumedia-overview-plugin-actions">
        <p>
            <a href="<?php echo admin_url('admin.php?page=sumedia&plugin=urlify'); ?>"><?php echo __('Configuration', 'sumedia-urlify'); ?></a>
        </p>
    </div>
</div>
